name = "halcyon"
description = "A minimal mobile-friendly, light/dark Zola theme inspired by Halcyon."
license = "Apache-2.0"
homepage = "https://github.com/dbarenholz/halcyon-zola"
min_version = "0.20.0"
demo = "https://example.com"
author = "dbarenholz"
