name = "halcyon"
description = "A Zola theme inspired by the Halcyon theme."
license = "Apache-2.0"
homepage = "https://github.com/dbarenholz/halcyon-zola"
min_version = "0.22.1"
demo = "https://dbarenholz.github.io/halcyon-zola/"
author = "dbarenholz"
